language: node_js

node_js:
  - "10.23"
  
jdk:
  - openjdk11

jobs:
  include:
    - stage: test
      script: npm run format:check
    -
      script: npm run lint
    - 
      script: npm run cspell

    - stage: release
      before_install:
        - npm run dynamodb &
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npx semantic-release