language: node_js
node_js:
  - "10.23"
  
jdk:
  - openjdk11

before_install:
  - npm install -g typescript
  - java -Djava.library.path=./res/DynamoDBLocal/DynamoDBLocal_lib -jar res/DynamoDBLocal/DynamoDBLocal.jar -sharedDb -inMemory -port 3000 &

install:
  - npm install
  - tsc
  - npm test

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
