language: node_js

node_js:
  - "10.23"
  
jdk:
  - openjdk11

jobs:
  include:
    - stage: release
      before_install:
        - java -Djava.library.path=./res/DynamoDBLocal/DynamoDBLocal_lib -jar res/DynamoDBLocal/DynamoDBLocal.jar -sharedDb -inMemory -port 3000 &
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npx semantic-release
