language: node_js

node_js:
  - "10.23"
  
jdk:
  - openjdk11

jobs:
  include:
    - stage: release
      install:
        - npm install
      after_install:
        - npm run dynamodb &
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npx semantic-release
