language: node_js

node_js:
  - "12.20.1"
  
jdk:
  - openjdk11

jobs:
  include:
    - stage: test
      name: format
      script: npm run format:check
    -
      name: lint
      script: npm run lint
    - 
      name: spelling
      script: npm run cspell
    - 
      name: examples
      script: npm run test:examples
    -
      name: test
      before_script: npm run dynamodb &
      script: npm run test

    - stage: release
      before_install: npm run dynamodb &
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npx semantic-release