language: node_js
node_js:
  - "8.10"
  
jdk:
  - openjdk11

before_install:
  - npm install -g typescript
  - java -Djava.library.path=./res/DynamoDBLocal/DynamoDBLocal_lib -jar res/DynamoDBLocal/DynamoDBLocal.jar -sharedDb -inMemory -port 3000 &

install:
  - npm install
  - tsc
  - npm test