language: node_js

node_js:
  - "10.23"
  
jdk:
  - openjdk11

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
        - npm run dynamodb &
        script:
          npx semantic-release
